# Digital_Twin/grafana/provisioning/datasources/datasource.yml
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090  # Connects to the 'prometheus' service in docker-compose
    isDefault: true
    editable: false